config/routes.rb
Traces::Application.routes.draw do
  mount API::Traces => '/api'

  devise_for :users

  resources :diaries
  resources :articles do
    resources :comments
  end
  resources :comments

  root :to => 'backbone#index'

  get '/drafts' => 'articles#drafts'
  get '/feed' => 'articles#feed'
  get '/sitemap' => 'sitemap#index'

  get "/:year((/:month(/:day))(/:slug))" => "articles#show_all",
  :constraints => { :year => /\d{4}/, :month => /0[1-9]|1[0-2]/, :day => /0[1-9]|1\d|2\d|3[0-1]/ }

  get "/:year(/:month)/:slug" => redirect("/:year((/:month(/:day))(/:slug))"),
  :constraints => { :year => /\d{4}/, :month => /0[1-9]|1[0-2]/, :slug => /\d{3,}|\D+/ }

  get '/users/signed_in_check' => 'backbone#signed_in_check'
end

app/models/article.rb
class Article < CouchRest::Model::Base

  property :slug
  property :title
  property :content
  property :author
  property :is_draft, TrueClass, default: false
  property :format,   String,    default: 'Markdown'
  property :tags,     [String]

  timestamps!

  validates_presence_of :title, :slug
  validates_uniqueness_of :slug

  def type
    self["couchrest-type"]
  end

  design do
    view :by_published_at,
      map: "
        function(doc) {
          if ((doc['couchrest-type'] == 'Article') && (doc['is_draft'] != true) && (doc['created_at'] != null)) {
            emit(doc['created_at'], 1);
          }
        }",
      reduce: "_sum"

    view :by_title
    view :by__id
    view :by_slug
    view :by_slug_and_published_at,
      map: "
        function(doc) {
          if ((doc['couchrest-type'] == 'Article') && (doc['is_draft'] != true) && (doc['slug'] != null) && (doc['created_at'] != null)) {
            emit([doc.slug, doc.created_at.substr(0, 10)], 1);
          }
        }",
      reduce: "_sum"

    view :article_comments,
      map: "
        function(doc) {
          if ((doc['couchrest-type'] == 'Comment')) {
            emit([doc.article_id, doc.created_at], 1);
          }
        }",
      reduce: "_sum"
  end

  def self.parse_time(params = { year: 0 })
    year = params[:year].to_i
    # only year param available
    if params[:month].blank?
      begin_time = Date.new(year)
      end_time = Date.new(year + 1)
    else
      month = params[:month].to_i

      if params[:day].blank?
        begin_time = Date.new(year, month)
        end_time = month == 12 ? Date.new(year + 1) : Date.new(year, month + 1)
      else
        begin_time = end_time = Date.new(year, month, params[:day].to_i)
      end
    end

    [begin_time, end_time]
  end

  def self.create_by_user(params, user)
    param_article = params[:article] || params[:diary]
    article = new(param_article)
    article.author = user.id
    article.is_draft = params[:commit] == "Save" ? true : false
    article.save!
    article
  end

  def self.articles_by_time_slug(params)
    begin_time, end_time = self.parse_time(params)

    if params[:slug]
      articles = self.by_slug_and_published_at.
        startkey([params[:slug], begin_time]).
        endkey([params[:slug], end_time])
    else
      articles = self.by_published_at.
        startkey(begin_time).
        endkey(end_time)
    end
  end

  def attachments=(attachments)
    attachments.each do |attachment|
      self.create_attachment(:file => attachment, :name => attachment.original_filename)
    end
  end

  def tag_attributes=(tag_attributes)
    tag_attributes.split(/,\s*/).each do |tag|
      tags << tag unless tags.include?(tag)
    end
  end

  def to_param
    slug
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  respond_to :html
  layout :layout_by_google_analytics
  before_action :authenticate_user!, :except => [:index, :show, :show_redirect, :show_all, :feed, :more]
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  def index
    #TODO: make limit configurable || params[:limit]
    @articles = Article.by_published_at.descending.limit(5).skip(params[:skip].to_i)
  end

  def drafts
    #TODO: make limit configurable || params[:limit]
    @articles = Article.by_saved_at.descending.limit(10)
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.create_by_user(params, current_user)
    respond_with(@article)
  end

  def edit
  end

  def update
    @article.update_attributes(params[:article])
    respond_with(@article)
  end

  def show
    redirect_to article_slug(@article) unless @article.is_draft

    @comments = Article.article_comments.
      startkey([@article.id]).
      endkey([@article.id, Time.now])
  end

  def show_all
    @articles = Article.articles_by_time_slug(params)

    if @articles.count == 1
      @article = @articles.first
      @comments = Article.article_comments.
        startkey([@article.id]).
        endkey([@article.id, Time.now])
    end

    render_404 if @article.blank? && @articles.blank?
  end

  def feed
    @articles = Article.by_published_at.descending.limit(5).all

    respond_to do |format|
      format.html do
        redirect_to feed_path(:format => :atom), :status => :moved_permanently
      end
      format.xml do
        redirect_to feed_path(:format => :atom), :status => :moved_permanently
      end
      format.atom
    end
  end

  private
    def set_article
      @article = Article.by_slug.key(params[:id]).first
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
  def title_content(article)
    content_for :title do
      article.title || 'Traces'
    end
  end
end

app/views/articles/_article.html.erb
<article>
  <section class="post_title">
    <h1><%= link_to article.title, article_relative_slug(article) %></h1>
  </section>
  <section class="post_meta">
    <p>
    Created @
    <time datetime="<%= article.created_at.to_date.to_s %>">
      <%= Time.zone.at(article.created_at.to_time).to_datetime.to_formatted_s(:long) %>
    </time>
    </p>
  </section>
  <section class="post_content">
    <%=raw Kramdown::Document.new(extract_content(article)).to_html%>
    <% if user_signed_in? %>
      <%= link_to "edit", edit_article_path(article.slug) %>
    <% end %>
  </section>
</article>

app/views/articles/_form.html.erb
<%= form_for article, :html => {:class => "form-horizontal", :multipart => true} do |f| %>
  <fieldset>
    <div class="control-group">
      <%= f.label :title, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :title, :class =>"input-xlarge" %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :slug, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :slug, :class =>"input-xlarge" %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :content, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_area :content, :class =>"input-xlarge" %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :tag_attributes, "Tags(seperated by comma)", :class => 'control-label' %>
      <div class="controls">
        <%= text_area_tag("article[tag_attributes]") %>
      </div>
    </div>
    <div class="control-group">
      <%= label_tag 'article_attachments_', "File:", :class => 'control-label' %>
      <div class="controls">
        <%= file_field_tag("article[attachments][]") %>
      </div>
    </div>

    <div class="form-actions">
      <%= f.submit "Save", :class => "btn" %>
      <%= f.submit "Save and Publish", :class => "btn btn-primary" %>
    </div>
  </fieldset>
<% end %>

app/views/articles/drafts.html.erb
<section id="contents">
  <% @articles.each do |article| %>
    <%= render article %>
  <% end %>
</section>

app/views/articles/edit.html.erb
<section id="contents">
  <h1>Update the Post</h1>
  <%= render 'form', :article => @article %>
</section>

app/views/articles/index.html.erb
<section id="contents">
  <% @articles.each do |article| %>
    <%= render article %>
  <% end %>
</section>

app/views/articles/new.html.erb
<div class="row">
  <div class="span12">
    <h2>Creating New Post</h2>
    <%= render 'form', :article => @article %>
  </div>
</div>

app/views/articles/show.html.erb
<%= title_content(@article) %>

<section id="contents">
  <%= render @article %>
</section>

<section id="comments">
  <h3>
    <span class="comments_count"><%= @comments.count %>
    <% if @comments.count > 1 %>
    Comments
    <% else %>
    Comment
    <% end %>
    </span>
    to
    <%= @article.title %></h3>
  </h3>
  <ol class="comments_list">
    <% @comments.each do |comment| %>
      <%= render comment %>
    <% end %>
  </ol>
  <%= render "comments/new_comment", :article => @article %>
</section>

app/views/articles/show_all.html.erb
<section id="contents">
  <% if @article.nil? %>
    <% @articles.each do |article| %>
      <%= render article %>
    <% end %>
  <% else %>
    <%= title_content(@article) %>
    <%= render @article %>
    <section class="comments">
      <h3>
        <span class="comments_count"><%= @comments.count %>
        <% if @comments.count > 1 %>
        Comments
        <% else %>
        Comment
        <% end %>
        </span>
        to
        <%= @article.title%></h3>
        <ol id="comments_list" class="comments_list">
          <% @comments.each do %>
            <%= render @comments %>
          <% end %>
        </ol>
      <%= render "comments/new_comment", :article => @article %>
    </section>
  <% end %>
</section>