config/routes.rb
Traces::Application.routes.draw do
  mount API::Traces => '/api'

  devise_for :users

  resources :diaries
  resources :articles do
    resources :comments
  end
  resources :comments

  root :to => 'backbone#index'

  get '/drafts' => 'articles#drafts'
  get '/feed' => 'articles#feed'
  get '/sitemap' => 'sitemap#index'

  get "/:year((/:month(/:day))(/:slug))" => "articles#show_all",
  :constraints => { :year => /\d{4}/, :month => /0[1-9]|1[0-2]/, :day => /0[1-9]|1\d|2\d|3[0-1]/ }

  get "/:year(/:month)/:slug" => redirect("/:year((/:month(/:day))(/:slug))"),
  :constraints => { :year => /\d{4}/, :month => /0[1-9]|1[0-2]/, :slug => /\d{3,}|\D+/ }

  get '/users/signed_in_check' => 'backbone#signed_in_check'
end

app/models/diary.rb
class Diary < Article

  design do
    view :by_created_at
    view :by_title
    view :by_slug
    view :by_slug_created_at,
      map: "
        function(doc) {
          if ((doc['couchrest-type'] == 'Diary') && (doc['slug'] != null) && (doc['created_at'] != null)) {
            emit([doc.slug, doc.created_at.substr(0, 10)], 1);
          }
        }",
      reduce: "_sum"
  end

end

app/controllers/diaries_controller.rb
class DiariesController < ArticlesController
  before_action :authenticate_user!
  before_action :set_diary, only: [:show, :edit, :update, :destroy]

  def index
    @diaries = Diary.by_created_at.descending.limit(5)
  end

  def new
    @diary = Diary.new
  end

  def create
    @diary = Diary.create_by_user(params, current_user)

    respond_with(@diary)
  end

  def edit
  end

  def update
    @diary.update_attributes(params[:diary])
    respond_with(@diary)
  end

  def show
  end

  private
    def set_diary
      @diary = Diary.by_slug.key(params[:id]).first
    end
end

app/views/diaries/_diary.html.erb
<article>
  <section id="post_meta">
    <p>
    Created @
    <time datetime="<%= diary.created_at.to_date.to_s %>">
      <%= Time.zone.at(diary.created_at.to_time).to_datetime.to_formatted_s(:long) %>
    </time>
    </p>
  </section>
  <section id="post_content">
    <h1><%= link_to diary.title, diary_path(diary) %></h1>
    <%=raw Kramdown::Document.new(extract_content(diary)).to_html%>
    <p>

    </p>
    <% if user_signed_in? %>
      <%= link_to "edit", edit_diary_path(diary.slug) %>
    <% end %>
  </section>
</article>

app/views/diaries/_form.html.erb
<%= form_for diary, :html => {:class => "form-horizontal", :multipart => true} do |f| %>
  <fieldset>
    <div class="control-group">
      <%= f.label :title, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :title, :class =>"input-xlarge" %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :slug, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :slug, :class =>"input-xlarge" %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :content, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_area :content, :class =>"input-xlarge" %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :tag_attributes, "Tags(seperated by comma)", :class => 'control-label' %>
      <div class="controls">
        <%= text_area_tag("diary[tag_attributes]") %>
      </div>
    </div>
    <div class="control-group">
      <%= label_tag 'diary_attachments_', "File:", :class => 'control-label' %>
      <div class="controls">
        <%= file_field_tag("diary[attachments][]") %>
      </div>
    </div>

    <div class="form-actions">
      <%= f.button "Save", :class => "btn" %>
      <%= f.button "Save and Publish", :class => "btn btn-primary" %>
    </div>
  </fieldset>
<% end %>

app/views/diaries/edit.html.erb
<h1>Update the Post</h1>

<%= render 'form', :diary => @diary %>

app/views/diaries/index.html.erb
<section id="contents">
  <% @diaries.each do |diary| %>
    <%= render diary %>
  <% end %>
</section>

app/views/diaries/new.html.erb
<div class="row">
  <div class="span12">
    <h2>New Diary</h2>
    <%= render 'form', :diary => @diary %>
  </div>
</div>

app/views/diaries/show.html.erb
<section id="contents">
  <%= render @diary %>
</section>