config/routes.rb
Traces::Application.routes.draw do
  mount API::Traces => '/api'

  devise_for :users

  resources :diaries
  resources :articles do
    resources :comments
  end
  resources :comments

  root :to => 'backbone#index'

  get '/drafts' => 'articles#drafts'
  get '/feed' => 'articles#feed'
  get '/sitemap' => 'sitemap#index'

  get "/:year((/:month(/:day))(/:slug))" => "articles#show_all",
  :constraints => { :year => /\d{4}/, :month => /0[1-9]|1[0-2]/, :day => /0[1-9]|1\d|2\d|3[0-1]/ }

  get "/:year(/:month)/:slug" => redirect("/:year((/:month(/:day))(/:slug))"),
  :constraints => { :year => /\d{4}/, :month => /0[1-9]|1[0-2]/, :slug => /\d{3,}|\D+/ }

  get '/users/signed_in_check' => 'backbone#signed_in_check'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= t(:blog_title) %></title>
  <%= stylesheet_link_tag "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tag %>
</head>
<body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

<div class="wrap">
<%= yield %>
</div>
</body>
</html>

app/views/layouts/articles.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : 'Traces' %></title>

  <%= auto_discovery_link_tag(:atom, feed_path) %>
  <%= auto_discovery_link_tag(:rss, feed_path) %>
  <%= stylesheet_link_tag "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tag %>

  <script type="text/javascript">

    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-498639-4']);
    _gaq.push(['_trackPageview']);

    (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();

  </script>

</head>
<body>
  <p class="notice" style="display: none"><%= notice %></p>
  <p class="alert" style="display: none"><%= alert %></p>
  <header>
    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <%= link_to t(:blog_title), root_url, { :class => "brand" } %>
          <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <div class="container nav-collapse">
            <div class="inner-links">
              <ul class="nav">
                <li><%= link_to "Home", root_url %></li>
                <li><%= link_to "About", "http://about.me/lainuo" %></li>
                <% if user_signed_in? %>
                <li><%= link_to "Diaries", diaries_path %></li>
                <li><%= link_to "New", new_diary_path %></li>
                <% end %>
              </ul>
            </div>
            <div class="divider">
              <ul class="nav">
                <li class="divider-vertical"></li>
              </ul>
            </div>
            <% if user_signed_in? %>
            <div id="sign-out-link">
              <ul class="nav pull-right">
                <li><%= link_to "Sign Out", destroy_user_session_path %></li>
              </ul>
            </div>
            <% else %>
            <div id="sign-in-link">
              <ul class="nav pull-right">
                <li><%= link_to "Sign In", new_user_session_path %></li>
              </ul>
            </div>
            <% end %>
            <div class="outside-links">
              <ul class="nav">
                <li><%= link_to image_tag("feed-icon-28x28.png", :size => "20x20", :alt => "Feed"), feed_path %></li>
                <li><%= link_to image_tag("twitter.png", :size => "20x20", :alt => "Twitter"), "http://twitter.com/lainuo" %></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </header>
  <div class="container">
    <%= yield %>
  </div>
  <footer>
    <div class="container">
      <div id="tools">
        <h3>Powered by</h3>
        <ul>
          <li><%= link_to image_tag("cloudant-logo.png", :height => "30", :alt => "Cloudant"), "https://cloudant.com/" %></li>
          <li><%= link_to image_tag("heroku-logo.png", :height => "30", :alt => "Heroku"), "http://heroku.com/" %></li>
          <li><%= link_to image_tag("rails.png", :height => "30", :alt => "Ruby on Rails"), "http://www.rubyonrails.org/" %></li>
        </ul>
      </div>
    </div>
  </footer>
</body>
</html>

app/views/layouts/articles_without_ga.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : 'Traces' %></title>

  <%= auto_discovery_link_tag(:atom, feed_path) %>
  <%= auto_discovery_link_tag(:rss, feed_path) %>
  <%= stylesheet_link_tag "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tag %>

</head>
<body>
  <p class="notice" style="display: none"><%= notice %></p>
  <p class="alert" style="display: none"><%= alert %></p>
  <header>
    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <%= link_to t(:blog_title), root_url, { :class => "brand" } %>
          <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <div class="container nav-collapse">
            <div class="inner-links">
              <ul class="nav">
                <li><%= link_to "Home", root_url %></li>
                <li><%= link_to "About", "http://about.me/lainuo" %></li>
                <% if user_signed_in? %>
                <li><%= link_to "Diaries", diaries_path %></li>
                <li><%= link_to "New", new_diary_path %></li>
                <% end %>
              </ul>
            </div>
            <div class="divider">
              <ul class="nav">
                <li class="divider-vertical"></li>
              </ul>
            </div>
            <% if user_signed_in? %>
            <div id="sign-out-link">
              <ul class="nav pull-right">
                <li><%= link_to "Sign Out", destroy_user_session_path %></li>
              </ul>
            </div>
            <% else %>
            <div id="sign-in-link">
              <ul class="nav pull-right">
                <li><%= link_to "Sign In", new_user_session_path %></li>
              </ul>
            </div>
            <% end %>
            <div class="outside-links">
              <ul class="nav">
                <li><%= link_to image_tag("feed-icon-28x28.png", :size => "20x20", :alt => "Feed"), feed_path %></li>
                <li><%= link_to image_tag("twitter.png", :size => "20x20", :alt => "Twitter"), "http://twitter.com/lainuo" %></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </header>
  <div class="container">
    <%= yield %>
  </div>
  <footer>
    <div class="container">
      <div id="tools">
        <h3>Powered by</h3>
        <ul>
          <li><%= link_to image_tag("cloudant-logo.png", :height => "30", :alt => "Cloudant"), "https://cloudant.com/" %></li>
          <li><%= link_to image_tag("heroku-logo.png", :height => "30", :alt => "Heroku"), "http://heroku.com/" %></li>
          <li><%= link_to image_tag("rails.png", :height => "30", :alt => "Ruby on Rails"), "http://www.rubyonrails.org/" %></li>
        </ul>
      </div>
    </div>
  </footer>
</body>
</html>

app/views/layouts/backbone.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= auto_discovery_link_tag(:atom, feed_path) %>
    <%= auto_discovery_link_tag(:rss, feed_path) %>
    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tag %>
    <title>Traces</title>
    <script type="text/javascript">

      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-498639-4']);
      _gaq.push(['_trackPageview']);

      (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();

    </script>
  </head>
  <body>
    <div id="loader"><div class="loading">Loading...</div></div>
    <header>
    </header>
    <div class="container">
      <section id="contents">
        <%= yield %>
      </section>
    </div>

    <footer>
    </footer>
  </body>
  <script type="text/javascript">
    $(function() {
      App.initialize();
    });
  </script>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= auto_discovery_link_tag(:atom, feed_path) %>
  <%= auto_discovery_link_tag(:rss, feed_path) %>
  <%= stylesheet_link_tag "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tag %>

  <% if controller_name == "sessions" and controller.action_name == "new"%>
  <title>Sign in</title>
  <% else %>
  <title><%= t(:blog_title) %></title>
  <% end %>
</head>
<body>
  <p class="notice" style="display: none"><%= notice %></p>
  <p class="alert" style="display: none"><%= alert %></p>
  <header>
    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <%= link_to t(:blog_title), root_url, { :class => "brand" } %>
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <div class="container nav-collapse">
            <div class="inner-links">
              <ul class="nav">
                <li><%= link_to "Home", root_url %></li>
                <li><%= link_to "About", "http://about.me/lainuo" %></li>
                <% if user_signed_in? %>
                <li><%= link_to "Diaries", diaries_path %></li>
                <li><%= link_to "New", new_diary_path %></li>
                <% end %>
              </ul>
            </div>
            <div class="divider">
              <ul class="nav">
                <li class="divider-vertical"></li>
              </ul>
            </div>
            <% if user_signed_in? %>
            <div id="sign-out-link" class="invisible">
              <ul class="nav pull-right">
                <li><%= link_to "Sign Out", destroy_user_session_path %></li>
              </ul>
            </div>
            <% else %>
            <div id="sign-in-link">
              <ul class="nav pull-right">
                <li><%= link_to "Sign In", new_user_session_path %></li>
              </ul>
            </div>
            <% end %>
            <div class="outside-links">
              <ul class="nav">
                <li><%= link_to image_tag("feed-icon-28x28.png", :size => "20x20", :alt => "Feed"), feed_path %></li>
                <li><%= link_to image_tag("twitter.png", :size => "20x20", :alt => "Twitter"), "http://twitter.com/lainuo" %></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </header>
  <div class="container">
    <%= yield %>
  </div>
  <footer>
    <div class="container">
      <div id="tools">
        <h3>Powered by</h3>
        <ul>
          <li><%= link_to image_tag("cloudant-logo.png", :height => "30", :alt => "Cloudant"), "https://cloudant.com/" %></li>
          <li><%= link_to image_tag("heroku-logo.png", :height => "30", :alt => "Heroku"), "http://heroku.com/" %></li>
          <li><%= link_to image_tag("rails.png", :height => "30", :alt => "Ruby on Rails"), "http://www.rubyonrails.org/" %></li>
        </ul>
      </div>
    </div>
  </footer>
</body>
</html>

app/views/layouts/diaries.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tag %>

  <% if controller.action_name == "new" or controller.action_name == "create"%>
    <title>New Diary</title>
  <% else %>
    <% if @diaries %>
      <title>Diaries | <%= t(:blog_title) %></title>
    <% else %>
      <title><%= @diary.title %> | Diaries | <%= t(:blog_title) %></title>
    <% end %>
  <% end %>

</head>
<body>
  <p class="notice" style="display: none"><%= notice %></p>
  <p class="alert" style="display: none"><%= alert %></p>
  <header>
    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <%= link_to t(:blog_title), root_url, { :class => "brand" } %>
          <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <div class="container nav-collapse">
            <div class="inner-links">
              <ul class="nav">
                <li><%= link_to "Home", root_url %></li>
                <li><%= link_to "About", "http://about.me/lainuo" %></li>
                <% if user_signed_in? %>
                <li><%= link_to "Diaries", diaries_path %></li>
                <li><%= link_to "New", new_diary_path %></li>
                <% end %>
              </ul>
            </div>
            <div class="divider">
              <ul class="nav">
                <li class="divider-vertical"></li>
              </ul>
            </div>
            <% if user_signed_in? %>
            <div id="sign-out-link">
              <ul class="nav pull-right">
                <li><%= link_to "Sign Out", destroy_user_session_path %></li>
              </ul>
            </div>
            <% else %>
            <div id="sign-in-link">
              <ul class="nav pull-right">
                <li><%= link_to "Sign In", new_user_session_path %></li>
              </ul>
            </div>
            <% end %>
            <div class="outside-links">
              <ul class="nav">
                <li><%= link_to image_tag("feed-icon-28x28.png", :size => "20x20", :alt => "Feed"), feed_path %></li>
                <li><%= link_to image_tag("twitter.png", :size => "20x20", :alt => "Twitter"), "http://twitter.com/lainuo" %></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </header>
  <div class="container">
    <%= yield %>
  </div>
  <footer>
    <div class="container">
      <div id="tools">
        <h3>Powered by</h3>
        <ul>
          <li><%= link_to image_tag("cloudant-logo.png", :height => "30", :alt => "Cloudant"), "https://cloudant.com/" %></li>
          <li><%= link_to image_tag("heroku-logo.png", :height => "30", :alt => "Heroku"), "http://heroku.com/" %></li>
          <li><%= link_to image_tag("rails.png", :height => "30", :alt => "Ruby on Rails"), "http://www.rubyonrails.org/" %></li>
        </ul>
      </div>
    </div>
  </footer>
</body>
</html>